### ISSUE TITLE
Exception on import of _frames

### ISSUE THREAD

**Issue by ellinorcrux** [ni/nixnet-python#116]
Getting an Exception on import from _frames module without a helpful error message. 

## traceback: 

```
  File "ni_xnet_transport.py", line 7, in <module>
    from nixnet import FrameInStreamSession, FrameOutStreamSession
  File "C:\Python27\lib\site-packages\nixnet\__init__.py", line 9, in <module>
    from nixnet.session import *  # NOQA: F401, F403
  File "C:\Python27\lib\site-packages\nixnet\session.py", line 11, in <module>
    from nixnet._session import frames as session_frames
  File "C:\Python27\lib\site-packages\nixnet\_session\frames.py", line 8, in <mo
dule>
    from nixnet import _frames
  File "C:\Python27\lib\site-packages\nixnet\_frames.py", line 15, in <module>
    nxFrameFixed_t = struct.Struct('QIBBBB8s')  # NOQA: N801
TypeError: Struct() argument 1 must be string, not unicode
```

- OS: Windows 7
- Python version: 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]
- NI-XNET version: nixnet (0.1.0.dev2) (the one from today), XNET drivers: version 16

### Installed packages and version
backports-abc (0.5)
backports.ssl-match-hostname (3.5.0.1)
certifi (2017.4.17)
chardet (3.0.4)
click (6.7)
enum34 (1.1.6)
Flask (0.12.2)
future (0.16.0)
fuzzywuzzy (0.15.1)
hoplite (15.0.0.dev21)
idna (2.5)
itsdangerous (0.24)
Jinja2 (2.9.6)
labview-automation (15.0.0.dev23)
labview-io (0.0.4)
MarkupSafe (1.0)
nidaqmx (0.5.2)
nifpga (17.0.0.post2)
nixnet (0.1.0.dev2)
numpy (1.13.0)
pip (9.0.1)
psutil (5.2.2)
PyDAQmx (1.3.2)
pymongo (3.4.0)
pyserial (3.3)
PyVISA (1.8)
pywin32 (221)
requests (2.18.1)
robotframework (3.0.2)
setuptools (25.2.0)
singledispatch (3.4.0.3)
six (1.10.0)

**Comment by epage** [comment]
Hey, thanks for letting us know about this!

My suspicion is that this was an issue fixed between version of Python 2.7.  For example
```
> python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.Struct(u'Q')
<Struct object at 0x02EEAA40>
>>> quit()
```
(The `u` in `u'Q'` to simulated `from __future__ import unicode_literals` being enabled)

Would you prefer to upgrade (and we document needing "the latest" python 2.7) or for us to fix this?

**Comment by epage** [comment]
Found it!

>  What's New in Python 2.7.7 release candidate 1?
> ===============================================
> *Release date: 2014-05-17*
...
> - Issue #19099: The struct module now supports Unicode format strings.

**Comment by ellinorcrux** [comment]
OK thanks! We'll upgrade Python. Maybe have a more helpful message if that comes up?
