### ISSUE TITLE
Printing a frame object does not print payload values

### ISSUE THREAD

**Issue by KilometersG** [ni/nixnet-python#170]
I reproduced this issue using the can_frame_queued_io.py example. My only modifications were to remove the __future__ and six imports and use the built in functions. 

When I print a frame object I get the full information on the frame including Arb ID, Echo setting, Type, and timestamp, but the printed string always ends with "payload=...)".

I have reproduced this with both PrettyPrinter and the default print function. I confirmed that if you print frame.payload the full payload information does print. I also tried printing a string longer then the CAN frame to make sure my IDE didn't have a setting to cut off strings beyond a certain length (it does not cut off long strings).

- OS: Windows 7 Professional 64-bit
- Python version: 3.5.3 
- IDE: Pycharm Community Edition 2017.2
- NI-XNET version: 17.0
- Hardware: PXIe-8510/6 

*TODO:* paste the output from
```bash
$ python -m pip list
```
enum34 <1.1.6>
nixnet <0.1.0>
pip <9.0.1>
setuptools <28.8.0>
six <1.10.0>
typing <3.6.1>

**Comment by epage** [comment]
Thank you for providing feedback on this.

I was concerned about how big the payload might be (like with CAN FD or J1939) and decided to leave it off (see [types.py](https://github.com/ni/nixnet-python/blob/master/nixnet/types.py#L360)).  I assumed it'd be better for people to print the payload separately rather than getting overwhelmingly large output text that in aggregate might obscure the more critical information.

Some ideas I've come up with for this
- Have `__repr__` only print echo/type if it is non-default
  - Includes defining a default for `type` (`CAN_DATA` is probably best)
  - Unfortunately, printing lines of frames won't align as well
- Include the payload but cap its size, ending with a `...` if its too big
  - Maybe if it goes above 8 bytes, show 5 + `...` (so it still totals 8).

Any thoughts on the trade offs of those?  Any other ideas (including just ignoring the length of the `repr` and just showing it all)?

**Comment by KilometersG** [comment]
I'm trying to think through customer expectations. The reason I posted this as an issue is because this is in an example that's setup to do a loopback test. I would expect a loopback test to show the payload sent and payload received to verify proper communication.  In the short term, simply adding a print(frame.payload) to the examples would work.

Long term I like your second suggestion. If that was the case I would say it's important that we document in an easy to find place something along the lines of "For full payload readout print frame.payload" or something like that. 

As for your first suggestion, in my experience anyone wanting the echo and type of the frame will explicitly ask for it. The customers I've worked with do not commonly pull out those properties in LabVIEW XNET programming. More often than not they just want the payload. I would say these two properties are low priority for printing.

**Comment by epage** [comment]
So it sounds like the issue is not as much what gets printed for a frame but how the examples are setup?

**Comment by KilometersG** [comment]
I'd say that's part of the issue, but the current implementation isn't optimal. I ran this by some of my colleagues in SE to see what their experience with customers has been. They should be posting on this thread soon.

**Comment by AndrewHeim** [comment]
I'd rather not print the frame up to a certain length and then end with a "...".  Either we should always dump it all regardless of size, or not return the payload at all there.  Anything else would be inconsistent.

Returning the payload only to a certain length will likely lead to a case of someone testing things with a small payload, and then having trouble later on when they assumed it would work for a larger payload.  Another option there is to have it return a "payload too big" error if the frame is too big.  At least that wouldn't lead to silently inconsistent logs.  Though, that would also be strange - it wouldn't really be reporting a problem with the frame ("payload too big"), but with this function not wanting to give you too much text.  In the end, either of those is a bit inconsistent.

I'd rather it give you payload size in lieu of the payload.  That way, printing the frame object gives you all of the useful metadata without giving you the actual frame payload.  The payload is only (but dependably) accessible in frame.payload, no matter the size.  Also, print(frame) would give you enough to perform a cursory diagnostic and some info on the payload.

How does that sound?

**Comment by epage** [comment]
>  Another option there is to have it return a "payload too big" error if the frame is too big. At least that wouldn't lead to silently inconsistent logs. 

Something to keep in mind is that the built-in support for printing a frame is meant as a debug helper and is not meant for parsing or UX.  It should not error like that.  Those are policies left to the user to decide.  To be clear, this is a python convention I'm speaking of and not some assumption I'm making on how the customer will use the API.

> I'd rather it give you payload size in lieu of the payload. 

I think this could be reasonable.
