### ISSUE TITLE
Example programmatic_database_usage.py has incorrect hard-coded path to database

### ISSUE THREAD

**Issue by d-bohls** [ni/nixnet-python#215]
nixnet-python/nixnet_examples/programmatic_database_usage.py, line 18 assigns an incorrect path. Should be as follows:

\- database_filepath = os.path.join(os.path.dirname(\_\_file\_\_), 'nixnet_examples\\databases\\custom_database.dbc')
\+ database_filepath = os.path.join(os.path.dirname(\_\_file\_\_), 'databases\\custom_database.dbc')

We should also determine why this issue wasn't identified by automated tests.

**Comment by jashnani** [comment]
The test file that is supposed to run examples lives here:
nixnet-python/tests/test_examples.py

We should check to see if this test is currently being run with our CIs. If not, we should consider adding it there so we catch these type of things automatically.

**Comment by epage** [comment]
The examples are run with the driver mocked out.
- Examples can be verified in situations without required hardware present (don't have to wait for CI)
- Testing examples with a real driver is more complicated.  It might require changing the examples to be more "testable" which might put them at odds with their purpose of being examples.

**Comment by epage** [comment]
See https://github.com/ni/nixnet-python/blob/master/tests/test_examples.py
