### ISSUE TITLE
Documentation should encourage restricting install to compatible versions

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#220]
This project is following semver.  The documentation should encourage the user to follow best practices, including helping them from accidentally upgrade to an incompatible version until they are ready

For example, instead of 
```bash
$ python -m pip install nixnet
```
have
```bash
$ python -m pip install nixnet~=0.2.0
```

According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release), the compatible release version specifier will translate from `~=0.2.0` to `>=0.2.0,==0.2.*`

**Comment by epage** [comment]
The downside is that you'll need to remember to update this.

One approach is to update [MAINTAINING](https://github.com/ni/nixnet-python/blob/master/MAINTAINING.rst) with a note to update this.

**Comment by d-bohls** [comment]
Is there any concern that users might be confused if we lead them to install software the lags the API documentation on readthedocs?

Would it be bad practice to show them both options?

**Comment by epage** [comment]
This highlights an interesting conflict.

iirc readthedocs "latest" (which we link to) reflects master.  Our instructions specify installing the package using pip.  pip will only have the last published version.  The user might get confused as to functionality in the docs but not in the API.

So from this, it seems like we should
- Be fine to have a version specifier in the docs because that is the only version the user can actually install with pip
- We should, by default, link to the last package's docs and not master's docs
- It could be nice (somewhere) to also link to master's docs

**Comment by d-bohls** [comment]
So it sounds like we already lead them to install software that is probably older than what we link to on readthedocs.

Perhaps we should say something like:

install the latest released version:
- pip directions to latest released version
- readthedocs link to the latest released version

install latest version:
- directions to clone and use the latest version
- readthedocs link to the latest version

Is that possible?

**Comment by epage** [comment]
In following the open source mantra of "release early, release often", ideally the window of this being a problem is small.

One problem is that the ["Quick Start"](https://nixnet.readthedocs.io/en/latest/?badge=latest) (see also [README](https://github.com/ni/nixnet-python)) is meant to be that and should *not* go into gory details about how to install.  That is what the [Installation](https://nixnet.readthedocs.io/en/latest/installation.html) page is for.

If anything, I'd recommend the docs links in the README point to the latest release and then we have a separate footnote somewhere about master / master's docs.  Not sure where this would go.

**Comment by d-bohls** [comment]
@jashnani and I agreed to defer this out until after the next release. We both feel that accidental upgrade becomes more of a concern as we near the 1.0 release.

**Comment by d-bohls** [comment]
MI has fixed this issue in their repo:

https://github.com/ni/nimi-python/issues/734
