### ISSUE TITLE
Consider renaming the nixnet.db namespace to nixnet.database

### ISSUE THREAD

**Issue by d-bohls** [ni/nixnet-python#221]
I'm increasingly tempted to suggest we do this rename based on the following:

1. When I look at existing namespaces and class names (http://nixnet.readthedocs.io/en/latest/api_reference.html), I only see one abbreviated.
2. When I compare things with the C API (nixnet.h), almost every abbreviation to 'db' is some variation of the prefix nx*db. When not used as a function or error prefix, 'database' is almost always spelled out explicitly.

As I understand it, renaming the namespace involves renaming the 'db' folder to 'database', which involves two options:

1. Renaming the folder and fixing code in a single push, which probably causes some git history (blame) to be lost.
2. Renaming the folder first, pushing, then pushing again the fixed namespaces. This may keep history but break git-bisect (binary search for bugs) in the case where it happens to land on the broken push.

Any thoughts on (a) whether to do the rename and (b) which rename method to proceed with?

FYI, I feel keeping history would be more valuable than worrying about an unlikely-to-hit breakage in git-bisect.

**Comment by epage** [comment]
Number one rule of source control: every commit is valid.  That wins out over the history part.  In particular, the history of this code is not too old and shouldn't be a problem.

**Comment by jashnani** [comment]
I agree with @epage , let's go with Option 1: Rename folder and fix code in one push.
