### ISSUE TITLE
Should nixnet.db.Database use in-memory database as default?

### ISSUE THREAD

**Issue by d-bohls** [ni/nixnet-python#222]
The FrameInStreamSession and FrameOutStreamSession sessions both default to the ':memory:' name for databases.

Should we also allow a default of ':memory:' for the parameter database_name in the nixnet.db.Database constructor?

This would further abstract python users from having to explicitly name ':memory:' in their code to access the in-memory database. I believe there would be no further need for users to use that particular string for the in-memory database.

**Comment by epage** [comment]
> Should we also allow a default of ':memory:' for the parameter database_name in the nixnet.db.Database constructor?

When determining defaults, we should look to the LabVIEW API for inspiration.  I'm assuming they chose their defaults for good reasons.  Any deviations should be explicitly called out and we should run by all of the appropriate people.

> This would further abstract python users from having to explicitly name ':memory:' in their code to access the in-memory database. I believe there would be no further need for users to use that particular string for the in-memory database.

My question would be is if `:memory:` is a sane / reasonable / expected default for Databases?  Sadly, I don't use them enough to know the workflows to determine that.

**Comment by d-bohls** [comment]
I learned a number of interesting things from talking with Jason Smith:

1. Jason pointed out that the stream sessions in the LV API default to to the `:memory:` database, so the python API matches there.
2. Jason told me that there is nothing special about `:memory:`. You can get an in-memory database by specifying `:anything:` (any name between colons). In-memory databases are process wide. They start out as an empty database, and retain any modifications until the last reference is closed. So, if two threads open the same in-memory database, they will share it and see any changes made by the other thread.

Also, I took a closer look at our API. Even if we allowed the Database class constructor to default to `:memory:`, you still have to pass a database name instead of a ref to session constructors. Do we also allow an optional parameter on those for the database name to be `:memory:`? If we did, it would then be less clear to the user that the session is using the same database created when they called database.Database(). It would only be clear if the user could pass a database object to the session, This is starting to get messy.

At this point, I don't think we should take any action on this issue.
