### ISSUE TITLE
Expose method on signal to get DBC value table

### ISSUE THREAD

**Issue by d-bohls** [ni/nixnet-python#226]
We need a way to get DBC value tables from a signal object. Perhaps a property or method on signal, like:

table = signal.dbc_value_table

This functionality is provided in the C API through mode 3 of nxdbGetDBCAttribute:

http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/nxdbgetdbcattribute/

It's worth noting for implementation purposes that DBC attributes and DBC value tables are separate concepts. This task is currently gated on finding a DBC containing one or more signal value tables for verification and testing.

**Comment by d-bohls** [comment]
Oops, fixed this in #227 but forgot to include in PR description.

**Comment by jashnani** [comment]
Fixed in #227.
