### ISSUE TITLE
Should values of DBC value tables be integers?

### ISSUE THREAD

**Issue by d-bohls** [ni/nixnet-python#229]
Currently, we treat the values of DBC value tables as strings. We have some evidence that they may be restricted to ints. We should verify whether or not the values are always of type integer.

**Comment by jashnani** [comment]
We tested this by hardcoding a signal value table in DBC file where values were of type string and float. In both cases, the driver seems to be converting them to an int and returning it back as a string.

Also, we noticed that if a DBC signal value table has an odd number of items, the driver ignores the last item and returns the rest; giving you an even item list for creating key-value pairings.

**Comment by d-bohls** [comment]
I discussed this with Waldemar M. He said if a DBC contains a signal value in the DBC signal value table that is not an integer, than that DBC is not a "well formed" file as defined by Vector.

Thus, we can expect that signal values are always integers.
