### ISSUE TITLE
Design OOP API for vertical slice

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#23]
Refactor the skeleton API to be OOP
- [x] #22 API is sufficient for examples
- [x] Basic session properties
- [x] Session sub-properties
- [x] Evaluate adding hierarchy to the properties
- [x] Read/write API

**Comment by epage** [comment]
For the read/write API, the thing I'm considering

We define a BytesBuffer and FloatBuffer.  Reading raw frame and reading of signals will use these and return the values contained in them.  Compared to these `read` functions, we'll have `read_into` functions that take in the buffers.  We then manipulate them as needed for the number of samples requested to use in our calls.  This allows buffer reuse for performance.

If possible, these buffer objects would mimic enough of numpy that read/write need for numpy to be a drop in replacement, if needed, without having a hard dependency on numpy.

**Comment by epage** [comment]
Additionally for read/write, unlike DAQmx, XNET works more like [`io`](https://docs.python.org/3.5/library/io.html#class-hierarchy), should we implement one of those interfaces?

**Comment by XNET-PSE** [comment]
I agree XNET works very much like a stream. Many of the interfaces are already implemented in the C api. Read, write, flush, etc. Implementing them in the Python API seems like a good fit.
