### ISSUE TITLE
Typo in the PXIexpress form factor constant

### ISSUE THREAD

**Issue by ulfglaeser** [ni/nixnet-python#252]
In nixnet._enums the form factor is declared as:
 
```
class DevForm(enum.Enum):
    '''Device physical form factor.'''
    PXI = _cconsts.NX_DEV_FORM_PXI
    PCI = _cconsts.NX_DEV_FORM_PCI
    C_SERIES = _cconsts.NX_DEV_FORM_C_SERIES
    PX_IE = _cconsts.NX_DEV_FORM_PX_IE
    USB = _cconsts.NX_DEV_FORM_USB
```
It should be     
`PXIE = _cconsts.NX_DEV_FORM_PXIE`
(no underscores)

**Comment by epage** [comment]
This is another word splitting issue.

I pre-populated the API from the C API.  This required me to guess at how to convert PascalCase to SCREAMING_CASE.  Acronyms, particularly mix case ones, make this difficult to guess intent.
