### ISSUE TITLE
database.cluster __repr__ exception

### ISSUE THREAD

**Issue by iwane-pl** [ni/nixnet-python#264]
- OS: Win10 Enterprise 16299
- Python version: 3.6.2
- NI-XNET version: 18.5
- nixnet-python version: 0.3.0

Trying to print cluster collection gives the following exception:

```
>>> print(xnetdb.clusters)
Traceback (most recent call last):
  File "C:\python-3.6.2\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-29c878fe8f37>", line 1, in <module>
    print(xnetdb.clusters)
  File "C:\python-3.6.2\lib\site-packages\nixnet\database\_collection.py", line 28, in __repr__
    return '{}(handle={0}, db_type={1})'.format(type(self).__name__, self._handle, self._type)
ValueError: cannot switch from automatic field numbering to manual field specification
```

**Comment by epage** [comment]
Thanks for reporting this!  Looks like it was introduced in #228.

Looks like this is [covered by our integration tests](https://github.com/ni/nixnet-python/blob/master/tests/test_database_cluster.py#L24) but it looks like our integration tests aren't being run against every PR anymore.

So in addition to fixing this specific issue, I think we should
- Audit the rest of #228 for any other mistakes likes this
- Look into the state of our integration tests

**Comment by d-bohls** [comment]
I was a little baffled as to how the integration tests could have missed this, as we run them locally for every PR. Also, while the automated integration testing has been spotty, it has been run against more recent PRs. The testing situation should be evaluated and improved.

That said, the above link from Ed covers _cluster.Cluster.__repr__. I think we are missing test coverage of _collection.DbCollection.__repr__ and that is how this managed to slip by.

**Comment by epage** [comment]
> I was a little baffled as to how the integration tests could have missed this, as we run them locally for every PR. Also, while the automated integration testing has been spotty, it has been run against more recent PRs. The testing situation should be evaluated and improved.

I guess I missed that.  I thought we had some limited reporting of integration tests to the PRs but when I looked in the PRs I didn't see them what I thought I had remembered.

**Comment by d-bohls** [comment]
You're remembering correctly that there is some limited reporting. E.g. - Jenkins was back to reporting on #258. #228 just occurred during a blackout period where it had stopped reporting. I think Ajay had to use his GitHub account on Jenkins to get it to report again. We had a couple of issues like this, so I may be mixing them up.

**Comment by iwane-pl** [comment]
You're welcome! It was a thing I stumbled upon during playing around with the package in the command line.
