### ISSUE TITLE
Incorrect Frame ID Mask

### ISSUE THREAD

**Issue by shmaller** [ni/nixnet-python#266]
In types.py line 183, _FRAME_ID_MASK is set to 0x3FF. This is only a 10-bit mask. As a result, an error is thrown prompting to set an extended ID bit when using 11-bit ID such as 0x400 (which is a valid standard frame).

Changing the _FRAME_ID_MASK to 0x7FF (11-bits) rectifies the issue.

**Comment by epage** [comment]
Here is some documentation listing the ID is 11 bits
http://zone.ni.com/reference/en-XX/help/372841T-01/nixnet/canframes/
