### ISSUE TITLE
CI failing on Travis for pypy builds

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#269]
I'm assuming this is because they are no longer supporting those versions of pypy.  We should look into upgrading.

**Comment by d-bohls** [comment]
One thing I noticed comparing to an old build:

Previously passing: https://travis-ci.org/ni/nixnet-python/jobs/439868039
Now failing: https://travis-ci.org/ni/nixnet-python/jobs/548766194

In the log for the passing one, there is a message in the log saying "Network availability confirmed.". That message is not in the failing log. I don't know if they just stopped printing that, or if there is a new requirement to get network access.

I also poked around to see, if support for older versions was removed, what versions are now supported. I haven't figured out how to determine that yet.

**Comment by epage** [comment]
Looks like unversioned pypy is still available, ie changing our travis.yml file from "pypy-5.6.0" to "pypy"

See https://docs.travis-ci.com/user/languages/python/#pypy-support

Versioned is nicer because it means the CI doesn't suddenly start failing if a new version breaks things.

At one point I came across a way to browse all their archives but can't find it anymore.
