### ISSUE TITLE
Create Frame Stream I/O Example

### ISSUE THREAD

**Issue by XNET-PSE** [ni/nixnet-python#33]
Ideally we want the examples to work straight out of the box with most devices in a loopback configuration. This will be a slightly modified version of the CAN Loopback Example which can be used as a starting point. It will effectively combine the CAN Frame Stream Output and CAN Frame Stream Input examples to run simultaneously

This will take #27 and add Output to it.

XNET Create Session (Frame Input Stream) using in-memory database on interface 1
XNET Create Session (Frame Output Stream) using in-memory database on interface 2
Set Property (Interface:CAN:Termination) for both interfaces
Set Property (Interface:CAN:Baudrate) for both interfaces since we are using in-memory database
XNET Start for both sessions
Loop{
XNET Write (Frame CAN) Payload: Counter
XNET Read (Frame CAN) Display scrolling frame data we transmit
}
XNET Clear
XNET Frame Type CAN
Timestamp

**Comment by epage** [comment]
Could you name specifically which example(s) you are wanting to use as inspiration for this?

**Comment by XNET-PSE** [comment]
CAN_Frame_Stream_Input example:
#include <stdlib.h>     // Include file for various functions
#include <stdio.h>      // Include file for printf
#include <conio.h>      // Include file for _getch/kbhit
#include <windows.h>    // Include file for Win32 time functions
#include "nixnet.h"     // Include file for NI-XNET functions and constants

//=============================================================================
// Static global variables
//=============================================================================
static nxSessionRef_t m_SessionRef = 0;

//=============================================================================
// Global functions declarations
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source);
int PrintTimestamp(nxTimestamp_t *Time);

//=============================================================================
// Main function
//=============================================================================
int main(void)
{
   // Declare all variables for the function
   unsigned int i = 0;
   unsigned int j = 0;
   int l_TypedChar = 0;
   char *l_pSelectedInterface = "CAN2";
   char *l_pSelectedDatabase = ":memory:";
   char *l_pSelectedCluster = "";
   char *l_pSelectedFrameList = "";

   u8 l_Buffer[250 * sizeof(nxFrameCAN_t)]; // Use a large buffer for stream input
   nxFrameVar_t *l_pFrame = NULL;
   u32 l_NumBytes = 0;
   u32 l_BaudRate = 125000;
   nxStatus_t l_Status = 0;

   // Display parameters that will be used for the example.
   printf("Interface: %s\nDatabase: %s\nBaudrate: %d\n", l_pSelectedInterface,
      l_pSelectedDatabase, l_BaudRate);

   // Create an XNET session in FrameInStream mode
   l_Status = nxCreateSession(l_pSelectedDatabase, l_pSelectedCluster,
      l_pSelectedFrameList, l_pSelectedInterface, nxMode_FrameInStream,
      &m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("Session created successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxCreateSession");
   }

   // We are not using a predefined database, so we need to set the Baud Rate
   l_Status = nxSetProperty(m_SessionRef, nxPropSession_IntfBaudRate,
      sizeof(u32), &l_BaudRate);
   if (nxSuccess == l_Status)
   {
      printf("Properties set successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxSetProperty");
   }

   printf("Logging all received frames. Press q to quit\n");
   printf("Timestamp\t\tID\tData\n");
   do
   {
      // Read the received frames into the buffer
      l_Status = nxReadFrame(m_SessionRef, l_Buffer, sizeof(l_Buffer),
         nxTimeout_None, &l_NumBytes);
      if (nxSuccess == l_Status)
      {
         l_pFrame = (nxFrameVar_t *)l_Buffer;

         // l_pFrame iterates to each frame. When it increments
         // past the number of bytes returned, we reached the end.
         while ((u8 *)l_pFrame < (u8 *)l_Buffer + l_NumBytes)
         {
            // Print timestamp, ID and payload
            PrintTimestamp(&l_pFrame->Timestamp);
            printf("\t%d\t", l_pFrame->Identifier);
            for (i = 0; i < l_pFrame->PayloadLength; ++i)
            {
               printf("%02X ", l_pFrame->Payload[i]);
            }
            printf("\n");

            // Go to next variable-payload frame.
            l_pFrame = nxFrameIterate(l_pFrame);
         }
         Sleep(1); // Wait 1 ms
      }
      else
      {
         DisplayErrorAndExit(l_Status, "nxReadFrame");
      }

      if (_kbhit())
      {
         l_TypedChar = _getch();
      }
   }
   while ('q' != tolower(l_TypedChar));

   printf("Data aquisition stopped.\n");

   // Clear the XNET session
   l_Status = nxClear(m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("\nSession cleared successfully!\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxClear");
   }

   return 0;
}

//=============================================================================
// Display Error Function
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source)
{
   char l_StatusString[1024];
   nxStatusToString(Status, sizeof(l_StatusString), l_StatusString);

   printf("\n\nERROR at %s!\n%s\n", Source, l_StatusString);
   printf("\nExecution stopped.\nPress any key to quit\n");

   nxClear(m_SessionRef);

   _getch();
   exit(1);
}

//=============================================================================
// Prints a timestamp to stdout
//=============================================================================
int PrintTimestamp(nxTimestamp_t *Time)
{
   SYSTEMTIME l_STime;
   FILETIME l_LocalFTime;
   /* This Win32 function converts from UTC (international) time
   to the local time zone.  The NI-XNET card keeps time in UTC
   format (refer to the description of nxTimestamp_t in
   the NI-XNET reference for Read functions). */
   FileTimeToLocalFileTime((FILETIME *)Time, &l_LocalFTime);

   /* This Win32 function converts an absolute time (FILETIME)
   into SYSTEMTIME, a structure with fields for year, month, day,
   and so on. */
   FileTimeToSystemTime(&l_LocalFTime, &l_STime);

   return printf("%02d/%02d/%04d %02d:%02d:%02d.%03d", l_STime.wMonth, l_STime.wDay,
      l_STime.wYear, l_STime.wHour, l_STime.wMinute, l_STime.wSecond,
      l_STime.wMilliseconds);
}

**Comment by XNET-PSE** [comment]
CAN Frame Stream Output example:
#include <stdlib.h>     // Include file for various functions
#include <stdio.h>      // Include file for printf
#include <conio.h>      // Include file for _getch/kbhit
#include <windows.h>    // Include file for Win32 time functions
#include "nixnet.h"     // Include file for NI-XNET functions and constants

#define NUM_FRAMES 2

//=============================================================================
// Static global variables
//=============================================================================
static nxSessionRef_t g_SessionRef = 0;

//=============================================================================
// Global functions declarations
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source);

//=============================================================================
// Main function
//=============================================================================
int main(void)
{
   // Declare all variables for the function
   unsigned int i = 0;
   unsigned int j = 0;
   int l_TypedChar = 0;
   char *l_pSelectedInterface = "CAN1";
   char *l_pSelectedDatabase = ":memory:";
   char *l_pSelectedCluster = "";
   char *l_pSelectedFrameList = "";
   u32 l_BaudRate = 125000;
   u32 l_NumberOfBytesForFrames = 0;
   u8 l_Buffer[NUM_FRAMES * sizeof(nxFrameCAN_t)];
   nxFrameVar_t *l_pFrame = NULL;
   nxStatus_t l_Status = 0;

   // Display parameters that will be used for the example.
   printf("Interface: %s\nDatabase: %s\nBaudrate: %d\n", l_pSelectedInterface,
      l_pSelectedDatabase, l_BaudRate);

   // Create an XNET session in FrameOutStream mode
   l_Status = nxCreateSession(l_pSelectedDatabase, l_pSelectedCluster,
      l_pSelectedFrameList, l_pSelectedInterface, nxMode_FrameOutStream,
      &g_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("Session created successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxCreateSession");
   }

   // We are not using a predefined database, so we need to set the Baud Rate
   l_Status = nxSetProperty(g_SessionRef, nxPropSession_IntfBaudRate,
      sizeof(u32), &l_BaudRate);
   if (nxSuccess == l_Status)
   {
      printf("Properties set successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxSetProperty");
   }

   // Get a pointer to the first frame's memory
   l_pFrame = (nxFrameVar_t *)l_Buffer;

   // Set the first frame's parameters (skipping the payload for now).
   // There are ways to programmatically get these parameters
   // using the objects properties. Here we hardcode them.
   l_pFrame->Timestamp = 0;
   l_pFrame->Flags = 0;
   l_pFrame->Identifier = 4;
   l_pFrame->Type = nxFrameType_CAN_Data;
   l_pFrame->PayloadLength = 8;

   // Iterate the pointer to the next frame
   l_pFrame = nxFrameIterate(l_pFrame);

   // Set the second frame's parameters (skipping the payload for now).
   l_pFrame->Timestamp = 0;
   l_pFrame->Flags = 0;
   l_pFrame->Identifier = 5;
   l_pFrame->Type = nxFrameType_CAN_Data;
   l_pFrame->PayloadLength = 2;

   // Get the actual size of the buffer used
   l_pFrame = nxFrameIterate(l_pFrame);
   l_NumberOfBytesForFrames = (u32)((u8 *)l_pFrame - (u8 *)l_Buffer);

   printf("Press q to quit.\n");

   // Main loop
   i = 0;
   do
   {
      // Update the payload of the first frame
      l_pFrame = (nxFrameVar_t *)l_Buffer;
      for (j = 0; j < l_pFrame->PayloadLength; ++j)
      {
         l_pFrame->Payload[j] = (u8)(j + i);
      }

      // Update the payload of the second frame
      l_pFrame = nxFrameIterate(l_pFrame);
      for (j = 0; j < l_pFrame->PayloadLength; ++j)
      {
         l_pFrame->Payload[j] = (u8)(j + i);
      }

      // Write the frame buffer
      l_Status = nxWriteFrame(g_SessionRef, l_Buffer,
         l_NumberOfBytesForFrames, 10.0);
      if (nxSuccess != l_Status)
      {
         DisplayErrorAndExit(l_Status, "nxWriteFrame");
      }
      printf("\rSent frames with payloads starting with %02X.", i);

      if (++i > 0xFF)
      {
         i = 0;
      }

      Sleep(100); // Wait 100 ms

      if (_kbhit())
      {
         l_TypedChar = _getch();
      }
   }
   while ('q' != tolower(l_TypedChar));

   // Clear the XNET session
   l_Status = nxClear(g_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("\nSession cleared successfully!\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxClear");
   }

   return 0;
}

//=============================================================================
// Display Error Function
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source)
{
   char l_StatusString[1024];
   nxStatusToString(Status, sizeof(l_StatusString), l_StatusString);

   printf("\n\nERROR at %s!\n%s\n", Source, l_StatusString);
   printf("\nExecution stopped.\nPress any key to quit\n");

   nxClear(g_SessionRef);

   _getch();
   exit(1);
}

**Comment by epage** [comment]
Fixed by #42
