### ISSUE TITLE
Create CAN Signal Single Point I/O example

### ISSUE THREAD

**Issue by XNET-PSE** [ni/nixnet-python#34]
Ideally we want the examples to work straight out of the box with most devices in a loopback configuration. This will be a slightly modified version of the CAN Loopback Example which can be used as a starting point. It will effectively combine the CAN Signal Single Point Input and CAN Signal Single Point Ouput examples to run simultaneously

XNET Create Session (Signal Input Single Point) using example database/signals on interface 1
XNET Create Session (Signal Output Single Point) using example database/signals on interface 2
Set Property (Interface:CAN:Termination) for both interfaces
XNET Start for both sessions
Loop{
Request input: Write new value or read current value
XNET Write (Frame CAN) Payload: Counter
XNET Read (Frame CAN) Display current value
}
XNET Clear

**Comment by epage** [comment]
Could you name specifically which example(s) you are wanting to use as inspiration for this?

**Comment by XNET-PSE** [comment]
"CAN Signal Single Point Input" and "CAN Signal Single Point Output"

**Comment by epage** [comment]
Is the recommendation to merge them or is this issue to add them both?

**Comment by XNET-PSE** [comment]
To merge them. We want one example that does input and output. We do not want separate examples for input and output. This approach reduces effort and is a better experience for the new user.

**Comment by XNET-PSE** [comment]
CAN Signal Single Point example:
#include <stdlib.h>     // Include file for various functions
#include <stdio.h>      // Include file for printf
#include <conio.h>      // Include file for _getch/kbhit
#include <windows.h>    // Include file for Win32 time functions
#include "nixnet.h"     // Include file for NI-XNET functions and constants

#define NUM_SIGNALS 2

//=============================================================================
// Static global variables
//=============================================================================
static nxSessionRef_t m_SessionRef = 0;

//=============================================================================
// Global functions declarations
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source);

//=============================================================================
// Main function
//=============================================================================
int main(void)
{
   // Declare all variables for the function
   char *l_pSelectedInterface = "CAN2";
   char *l_pSelectedDatabase = "NIXNET_example";
   char *l_pSelectedCluster = "CAN_Cluster";
   char *l_pSelectedSignalList = "CANEventSignal1,CANEventSignal2";
   f64 l_ValueBuffer[NUM_SIGNALS];
   nxTimestamp_t l_TimestampBuffer[NUM_SIGNALS];
   nxStatus_t l_Status = 0;

   // Display parameters that will be used for the example.
   printf("Interface: %s\nDatabase: %s\nSignal List: %s\n",
      l_pSelectedInterface, l_pSelectedDatabase, l_pSelectedSignalList);

   // Create an XNET session in SignalInSinglePoint mode
   l_Status = nxCreateSession(l_pSelectedDatabase, l_pSelectedCluster,
      l_pSelectedSignalList, l_pSelectedInterface, nxMode_SignalInSinglePoint,
      &m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("Session created successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxCreateSession");
   }

   printf("Press any key to read the latest signal values or q to quit\n");

   // Main loop
   while ('q' != tolower(_getch()))
   {
      // Read the latest signal data. The first read will also auto-start the
      // session and normally return the default values defined in the database.
      // Use the nxStart function to start the session before the initial read.
      l_Status = nxReadSignalSinglePoint(m_SessionRef, l_ValueBuffer,
         sizeof(l_ValueBuffer), l_TimestampBuffer, sizeof(l_TimestampBuffer));
      if (nxSuccess == l_Status)
      {
         // Print the values ignoring timestamps
         printf("Signals received:\n");
         printf("Signal 1: %f\n", l_ValueBuffer[0]);
         printf("Signal 2: %f\n\n", l_ValueBuffer[1]);
      }
      else
      {
         DisplayErrorAndExit(l_Status, "nxReadSignalSinglePoint");
      }
   }

   // Clear the XNET session
   l_Status = nxClear(m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("\nSession cleared successfully!\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxClear");
   }

   return 0;
}

//=============================================================================
// Display Error Function
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source)
{
   char l_StatusString[1024];
   nxStatusToString(Status, sizeof(l_StatusString), l_StatusString);

   printf("\n\nERROR at %s!\n%s\n", Source, l_StatusString);
   printf("\nExecution stopped.\nPress any key to quit\n");

   nxClear(m_SessionRef);

   _getch();
   exit(1);
}

**Comment by XNET-PSE** [comment]
CAN Signal Single Point Output example:
#include <stdlib.h>     // Include file for various functions
#include <stdio.h>      // Include file for printf
#include <conio.h>      // Include file for _getch/kbhit
#include <windows.h>    // Include file for Win32 time functions
#include "nixnet.h"     // Include file for XNET functions

#define NUM_SIGNALS 2

//=============================================================================
// Static global variables
//=============================================================================
static nxSessionRef_t m_SessionRef = 0;

//=============================================================================
// Global functions declarations
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source);

//=============================================================================
// Main function
//=============================================================================
int main(void)
{
   // Declare all variables for the function
   unsigned int i = 0;
   char *l_pSelectedInterface = "CAN1";
   char *l_pSelectedDatabase = "NIXNET_example";
   char *l_pSelectedCluster = "CAN_Cluster";
   char *l_pSelectedSignalList = "CANEventSignal1,CANEventSignal2";
   f64 l_ValueBuffer[NUM_SIGNALS];
   nxStatus_t l_Status = 0;

   // Display parameters that will be used for the example.
   printf("Interface: %s\nDatabase: %s\nSignal List: %s\n",
      l_pSelectedInterface, l_pSelectedDatabase, l_pSelectedSignalList);

   // Create an XNET session in SignalOutSinglePoint mode
   l_Status = nxCreateSession(l_pSelectedDatabase, l_pSelectedCluster,
      l_pSelectedSignalList, l_pSelectedInterface, nxMode_SignalOutSinglePoint,
      &m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("Session created successfully.\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxCreateSession");
   }

   printf("Press any key to transmit new signal values or q to quit\n");

   // Main loop
   while ('q' != tolower(_getch()))
   {
      l_ValueBuffer[0] = (f64)i;
      l_ValueBuffer[1] = (f64)(i * 10);

      // Update the signal data
      l_Status = nxWriteSignalSinglePoint(m_SessionRef, l_ValueBuffer,
         sizeof(l_ValueBuffer));
      if (nxSuccess == l_Status)
      {
         printf("Signals sent:\n");
         printf("Signal 1: %f\n", l_ValueBuffer[0]);
         printf("Signal 2: %f\n\n", l_ValueBuffer[1]);
         if (++i > 10)
         {
            i = 0;
         }
      }
      else
      {
         DisplayErrorAndExit(l_Status, "nxWriteSignalSinglePoint");
      }
   }

   // Clear the XNET session
   l_Status = nxClear(m_SessionRef);
   if (nxSuccess == l_Status)
   {
      printf("Session cleared successfully!\n");
   }
   else
   {
      DisplayErrorAndExit(l_Status, "nxClear");
   }

   return 0;
}

//=============================================================================
// Display Error Function
//=============================================================================
void DisplayErrorAndExit(nxStatus_t Status, char *Source)
{
   char l_StatusString[1024];
   nxStatusToString(Status, sizeof(l_StatusString), l_StatusString);

   printf("\n\nERROR at %s!\n%s\n", Source, l_StatusString);
   printf("\nExecution stopped.\nPress any key to quit\n");

   nxClear(m_SessionRef);

   _getch();
   exit(1);
}

**Comment by jashnani** [comment]
#60 fixes this
