### ISSUE TITLE
`Frame.pdu_*` properties should be considered for a tuple

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#53]
#52 adds `db.Frame`.  The pdu properties act as a parallel array.  These should be exposed as a `namedtuple`

**Comment by d-bohls** [comment]
Per the latest C API docs (17.0), it sounds like CAN and LIN are currently limited to a single PDU mapped to a frame.

http://zone.ni.com/reference/en-XX/help/372841P-01/nixnet/nxpropfrm_pdurefs/

Thus, the user's options are:

1. Map a single PDU to a frame.
2. Skip the PDU and add signals and subframes directly to the frame

Only FlexRay allows one or more PDUs to be mapped to one or more frames. We should verify that we can use a PDU with a frame in CAN/LIN, and see if this could possible change in the future. Options are:

1. Return a list of named tuples
2. Return a single named tuple
3. Keep the properties separate and return a single element (pdu, pdu_start_bit, pdu_update_bit)

Something to keep in mind: do we want functionality parity with the database editor? If the database editor allows multi-mapping between PDUs and frames, are how is the customer experience with our python API choices?

**Comment by lilesj** [comment]
CAN and LIN both require the "[PDUs required?](http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/propertyclusterpdusrequired/)" property to be false. I believe you can still use the database objects to create sessions etc. In LabVIEW we have the Create Session (PDU In/Out Single-Point) family of VIs that use PDUs as inputs and they do work with LIN and CAN so long as "PDUs required?" is false.

**Comment by d-bohls** [comment]
And, to be clear, `PDUs required?` is a read-only boolean property that is `False` when

- Only one PDU is mapped to the frame.
- This PDU is not mapped to other frames.
- The PDU Start Bit in the frame is 0.
- The PDU Update Bit is not used.

So, a very limited case, but it does sound possible for CAN/LIN in the C API as well.

**Comment by jashnani** [comment]
Fixed in #245
