### ISSUE TITLE
Implement minimal Database API functionality

### ISSUE THREAD

**Issue by lilesj** [ni/nixnet-python#77]
Implement the following functions from the database API:

- [ ] nxdbAddAlias64 - Allows the user to programmatically create database aliases given a file path
- [ ] nxdbRemoveAlias - Removes a database alias from the system.
- [ ] nxdbGetDatabaseList - Provides a list of aliases on the host PC that can be used by create session. The C function includes the option to return the list of databases on a remote RT system. While that functionality is not currently required the implementation should take this into consideration.
- [ ] nxdbGetDatabaseListSizes - This function returns the buffer size required to hold the entire list of databases on the system. Will probably need to be included in the implementation of nxdbGetDatabaseList.

**Comment by epage** [comment]
The question I have is if we need to support talking to RT systems.

Ideally, this would be represented on the `System` object but that would need to leave off the IP Address.

```python
with System() as system:
    print(list(system.databases)) # prints tuples of alias / path
    system.databases[alias] = path # add ... but what about baud rate?
    del system.database[alias]
```

How do you lookup the baud rate associted with a alias/database?

**Comment by epage** [comment]
Oh, only nxdbGetDatabaseList and Sizes take IP Address.  Maybe we can start with the OOP and do something different if/when RT is needed just for those functions.

**Comment by XNET-PSE** [comment]
The add alias function takes 4 different file extensions as input. The *.dbc format is the most common and it does not natively include information about the baudrate. Accordingly, the user must enter the associated baud rate information when the alias is added. Once the alias is added, the baud rate information will be available to the rest of the API.

The baud rate is tricky because as an integer it can be interpreted multiple ways (default or custom based on certain bits) just as the [Interface:64bit Baud Rate property](http://zone.ni.com/reference/en-XX/help/372841N-01/nixnet/propertysessioninterface64bitbaudrate/) can.

**Comment by epage** [comment]
>  Once the alias is added, the baud rate information will be available to the rest of the API.

Once I've added an alias, how do I use the API to read the configured baud rate?  Can I modify the baud rate after I've added the alias or do I need to remove/add?  If so, how?

**Comment by XNET-PSE** [comment]
A user would create a session using the database alias. Behind the scenes, the database file is read into memory and the associated baud rate is set. Then when a user calls get/set property with the session reference, the baudrate in memory is returned/overwritten.

The baudrate associated with the alias remains unchanged until the alias is removed and added again with a new baud rate.

**Comment by epage** [comment]
Let me see if I get this right
- Session's `Interface:64bit Baud Rate` is defaulted to the one associated with the alias.
- The only way to look up how the alias is configured is by creating a Session.
- You can only change the baud rate on the Session and not the Alias.

**Comment by XNET-PSE** [comment]
That sounds correct.

**Comment by epage** [comment]
Drat.  I was hoping I could make `System.databases` act like a dictionary mapping alias name to `(file path, baud rate)` but that requires me being able to look up the baud rate.

I guess we'll need an "add alias" function but then have the rest act like a dictionary of alias name to file path.

**Comment by XNET-PSE** [comment]
I edited the post above. Baud rate information is available through a database property but we would need to implement more of the database API for it to become available. Baud rate is a cluster property so we would need to implement nxdbGetProperty and the associated PropertyID(s) to make it work.

**Comment by epage** [comment]
Ok, so this [`baud_rate`](https://github.com/ni/nixnet-python/blob/master/nixnet/db/_cluster.py#L38) is the same baud rate.  Drat, that requires instantiating the database.  Oh well, still on plan B.
