### ISSUE TITLE
Should the API provide any convinience for reading trigger signals?

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#81]
Could the API provide a convenience for [reading](http://zone.ni.com/reference/en-XX/help/372841N-01/nixnet/nxreadsignalsinglepoint/) [trigger signals](http://zone.ni.com/reference/en-XX/help/372841N-01/nixnet/modesignalinputsinglepoint_c/)?  or would "the cure be worse than the disease"?

**Comment by XNET-PSE** [comment]
Trigger signals are not commonly used. Would the convenience have performance implications for the masses that outweigh the benefits for the few? How lightweight is the convenience?

**Comment by epage** [comment]
My concern isn't performance but how well the API could expose the concept.

I'll drop this then.
