### ISSUE TITLE
Implement read/write support for special can frames

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#82]
We should implement support for [Special frame types](http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/specialframes_c/)

**Comment by XNET-PSE** [comment]
Support should be prioritized in the following order:

1. Bus Error Frame - The fields in the payload are extremely useful for debugging problems with the network.
2. Start Trigger Frame - Critical for high accuracy time stamps.
3. Log Trigger Frame
4. Delay Frame

**Comment by epage** [comment]
#160 and and #144 resolved this for CAN frames. LIN frames will be added as part of the LIN work.
